<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HAQKA9K" name="TestParallelRuns" tests="2" failures="1" timestamp="18 Sep 2018 03:39:09 GMT" time="0.072" errors="0">
  <testcase name="sampleTest1" time="0.023" classname="testng.features.SampleTestClass1"/>
  <testcase name="sampleTest3" time="0.034" classname="testng.features.SampleTestClass2">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at testng.features.SampleTestClass2.sampleTest3(SampleTestClass2.java:14)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- sampleTest3 -->
</testsuite> <!-- TestParallelRuns -->
